### ISSUE TITLE
Words sorted by weight

### ISSUE THREAD

**Issue by devNoiseConsulting** [tabatkins/wordle-list#5]
Would it be possible to have a 2nd word list that is sorted by weight? I played around with making a list using the letter frequency in each spot to calculate a weight. Only problem I saw is that some words at the top of the list had the same letter twice. Which would be bad for an opening word. Just a thought.

```
cut -b1 words | sort | uniq -c > letter_frequency_1.txt
cut -b2 words | sort | uniq -c > letter_frequency_2.txt
cut -b3 words | sort | uniq -c > letter_frequency_3.txt
cut -b4 words | sort | uniq -c > letter_frequency_4.txt
cut -b5 words | sort | uniq -c > letter_frequency_5.txt
```

**Comment by 0x6772** [comment]
If you're trying to do what I think you're trying to do, you're better off rescoring after seeing the results from the prior guess (that is, filter out everything that doesn't meet the correct letters, does include the wrong letters, and includes the "move" letters in exactly the position they're in), since the letter frequency per position will have changed. This takes under a second in Python 3.7 on the 1.8 GHz Dual-Core Intel Core i5 in my aging MacBook Air: precalculating the lists doesn't make much sense.

**Comment by tabatkins** [comment]
Letter frequencies aren't really that useful here; it's a reasonable first approximation, but doesn't get you all the way there, and past the first guess will actively mislead you in optimal play. See explanations like <https://www.youtube.com/watch?v=v68zYyaEmEA> from 3b1b.

Or for more hands-on example, see the source code for <https://wordle-analyzer.com/> at <https://github.com/jakearchibald/wordle-analyzer>, which does something similar to what 3b1b talked about in their video.

Anyway, all this isn't the point of this repo; I intend it purely as an informational resource to let people (mostly, me) get access to all possible 5-letters words that Wordle will accept as guesses.
